import DOMPurify from 'isomorphic-dompurify';
import xss from 'xss';

/**
 * Strips HTML, malicious tokens, and script tags from a generic text input string.
 * Helps prevent XSS payload injection.
 * @param input raw string input from user
 * @returns sanitized string with completely stripped tags
 */
export const sanitizeInput = (input: string | undefined): string => {
    if (!input) return '';

    // 1st layer: use xss library to catch fundamental xss vectors
    const filtered = xss(input);

    // 2nd layer: isomorphic-dompurify for clean DOM-focused text payload removal
    return DOMPurify.sanitize(filtered, {
        ALLOWED_TAGS: [], // Effectively strips out all HTML tags
        ALLOWED_ATTR: [], // Effectively strips out all HTML attributes
    });
};

/**
 * Allow basic HTML tags for rich-text while stopping script and meta tags.
 * Use this when saving Markdown/HTML generated by WYSIWYG editors.
 * @param html rich text string
 * @returns safely formatted html
 */
export const sanitizeRichText = (html: string | undefined): string => {
    if (!html) return '';
    return DOMPurify.sanitize(html, {
        ALLOWED_TAGS: ['b', 'i', 'em', 'strong', 'a', 'p', 'br', 'ul', 'ol', 'li', 'h1', 'h2', 'h3'],
        ALLOWED_ATTR: ['href', 'target', 'rel'],
    });
};

/**
 * Simple password validator
 * Forces at least 1 uppercase, 1 lowercase, 1 number, 1 special char, 8+ length
 * @param pass string
 */
export const validatePasswordStrength = (pass: string): boolean => {
    const strongRegex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;
    return strongRegex.test(pass);
};
